# Визиты - https://yandex.ru/dev/metrika/doc/api2/logs/fields/visits.html
visits_columns_dict = {'ym:s:clientID': 'ID посетителя',
                       'ym:s:visitID': 'Идентификатор визита', 
                       'ym:s:startURL': 'Страница входа',
                       'ym:s:endURL': 'Страница выхода',
                       'ym:s:pageViews': 'Глубина просмотра',
                       'ym:s:goalsID': 'Цели',
                       'ym:s:visitDuration': 'Время на сайте',
                       'ym:s:lastTrafficSource': 'Источник трафика',
                       'ym:s:regionCountry': 'Страна',
                       'ym:s:regionCity': 'Город',
                       'ym:s:bounce': 'Отказность',
                       'ym:s:isNewUser': 'Первый визит посетителя',
                       'ym:s:operatingSystemRoot': 'Группа операционных систем',
                       'ym:s:lastSearchEngineRoot':'Поисковая система',
                       'ym:s:lastSearchEngine': 'Поисковая система (детально)',
                       'ym:s:lastSearchPhrase': 'Последняя значимая поисковая фраза',
                       'ym:s:browser': 'Браузер',
                       'ym:s:isNewUser': 'Первый визит посетителя',
                       'ym:s:parsedParamsKey1': 'Параметры визита, ур. 1',
                       'ym:s:parsedParamsKey2':	'Параметры визита, ур. 2'}

# Просмотры - https://yandex.ru/dev/metrika/doc/api2/logs/fields/hits.html
hits_columns_dict = {'ym:pv:clientID': 'Идентификатор пользователя на сайте',
                     'ym:pv:watchID': 'Идентификатор просмотра',
                     'ym:pv:date': 'Дата события', 
                     'ym:pv:title': 'Заголовок страницы',
                     'ym:pv:URL': 'Адрес страницы',
                     'ym:pv:deviceCategory': 'Тип устройства',
                     'ym:pv:regionCity': 'Город',
                     'ym:pv:regionCountry': 'Страна',
                     'ym:pv:isPageView': 'Просмотр страницы. Принимает значение 0, если хит не нужно учитывать как просмотр',
                     'ym:pv:link': 'Переход по ссылке',
                     'ym:pv:download': 'Загрузка файла',
                     'ym:pv:notBounce': 'Неотказ',
                     'ym:pv:httpError': 'Код ошибки',
                     'ym:pv:UTMContent': 'UTM Content',
                     'ym:pv:goalsID': 'Цели'}

sites_dict = {'56483272': 'Торуда',
              '50151718': 'Шведские стенки',
              '22033168': '500 диванов',
              '53011360': '500 люстр',
              '48455846': 'Кабинет-Офис',
              '21363337': 'Кабинетоф',
              '50617780': 'Компкресла',
              '53178196': 'Офис-экспресс',
              '46429848': 'Офисная мебель',
              '50153164': 'Печи-Камины',
              '52180510': 'Стулко',
              '50489554': 'Тепложар',
              '57645346': 'Торуда Казахстан',
              '86985335': 'Торуда-двор',
              '87970143': 'Торуда-двор Казахстан',
              '87312490': 'Торуда-парк',
              '87970383': 'Торуда-парк Казахстан',
              '51715535': 'Триал 4х4'}